name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Maven build & test
      - name: Build and Test
        run: mvn clean test

      # Post Maven test results in PR comments
      - name: Publish Maven Test Results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### Maven Test Results
            Build and tests passed ✅
          recreate: true

      # Code formatting & linting
      - name: Check Code Formatting
        run: mvn fmt:check

      - name: Lint Code
        run: mvn checkstyle:check

      # Validate PR description for JIRA ID
      - name: Validate PR Description
        uses: deepakputhraya/action-pr-description@v1.0.4
        with:
          regex: 'JIRA-\d+'
          errorMessage: 'PR description must include a JIRA ID'

      # Check unresolved review comments
      - name: Check unresolved review comments
        uses: marocchino/unresolved-comments@v2
